### ISSUE TITLE
Weird connection request accepted emails

### ISSUE THREAD

**Issue by pmonks** [finos/bot-github-chatops#25]
It has been reported that after the bot accepts a connection request, the email the requestor receives contains blanks:

> "" "" (via Symphony) <no-reply@symphony.com> has accepted your connection request.

**Comment by pmonks** [comment]
This seems to be a Symphony bug, as the bot itself doesn't construct these emails - it simply accepts any connection requests via the REST API (which indirectly causes Symphony to construct and send that email).

**Comment by pmonks** [comment]
This has been confirmed as Symphony issue BE-1515, and a fix is expected in v1.50.

**Comment by pmonks** [comment]
@maoo are you able to confirm with Symphony LLC whether this ever got fixed?

**Comment by maoo** [comment]
Email sent, you're in CC

**Comment by maoo** [comment]
Symphony Support confirmed this is fixed! Closing issue.
