### ISSUE TITLE
Documentation: replace RawGit with jsDelivr

### ISSUE THREAD

**Issue by maoo** [finos/bot-github-chatops#56]
RawGit - used in [README.md](README.md) - is sunsetting in October 2019; should be replaced with something else, ie jsdelivr; use https://www.jsdelivr.com/rawgit for an easy migration.

**Comment by nikoganev** [comment]
Created a PR: https://github.com/finos-fdx/bot-github-chatops/pull/59

**Comment by maoo** [comment]
done
