### ISSUE TITLE
"iv undefined error" on Travis CI builds

### ISSUE THREAD

**Issue by maoo** [finos/bot-github-chatops#62]
### Steps to Reproduce:
 1. See https://travis-ci.com/finos/bot-github-chatops/builds/124391931

### Expected Result:
A green build

### Actual Result:
Build fails with message `iv undefined`

### Environment:
Travis CI

### Additional Context:
Check https://github.com/travis-ci/travis.rb/issues/607

**Comment by pmonks** [comment]
See also [this recent build failure](https://travis-ci.com/finos/bot-github-chatops/builds/141847197#L215-L219).

**Comment by pmonks** [comment]
And [this one](https://travis-ci.com/github/finos/bot-github-chatops/builds/160078119).

@maoo any news on prioritisation of this issue?

**Comment by maoo** [comment]
Apologies for the long standing issue! Next week Im confident I can look at it.

Wondering if this is the issue - https://github.com/travis-ci/travis.rb/issues/607#issuecomment-463252868

TY for the heads up!

**Comment by pmonks** [comment]
Yep that could be it.  I wouldn't be surprised if migrating this repository between GitHub orgs requires all encrypted artifacts to be re-encrypted.

**Comment by maoo** [comment]
Fixed! See https://travis-ci.org/github/finos/bot-github-chatops
