### ISSUE TITLE
[meta] Someone is committing to master branch, bypassing dev

### ISSUE THREAD

**Issue by pmonks** [finos/bot-github-chatops#64]
Today I updated my local clone of dev, [upgraded some dependencies](https://github.com/finos/bot-github-chatops/commit/557eecd10de92233f003d108bbd6d77b75359340), [fixed the erroneous addition of a derived asset](https://github.com/finos/bot-github-chatops/commit/8ab64ad64c37cc28ef7f569428c7f6009ee246c5), and then noticed that `master` contained some commits that weren't in `dev`.  So I fixed that too.

This is contrary to the workflow defined for this project ([since clarified in the readme](https://github.com/finos/bot-github-chatops/tree/dev#contributing)), where all commits must come through the `dev` branch first, and are then "released" as a batch into the `master` branch.

It would be desirable to find out who is subverting this workflow, and then ensure that they follow it in future (and potentially also have their commit access to `master` removed).

**Comment by maoo** [comment]
Hi @pmonks !

First of all, thanks for fixing the issue; I am the only person who is maintaining this project, so I am probably the person who made the mistake, my apologies for not following the workflow.

As Project Lead (and part of the FDX PMC), I have requested the archival of this project (nobody from FINOS community is currently using - or contributing to - it; I don't see interest to activate this project in the next 9 months, hence the archival request) and the PMC voted in favour, so no need to make any change to the project workflow.

See https://groups.google.com/a/finos.org/forum/#!topic/fdx-pmc/Vd2NdolYYcw for more info about the voting.

I'm going to close this issue, as there's no work needed here.

**Comment by pmonks** [comment]
@maoo wrote:
> I am the only person who is maintaining this project

[Not exactly true... 😉](https://github.com/finos/bot-github-chatops/commits/dev)

**Comment by pmonks** [comment]
@maoo also, prior to requesting that the FDX PMC archive the project, it would have been best practice for you (as project lead) to coordinate that decision with the project team (as defined in the GitHub project's contributor list).  Unilateral decisions are kind of the antithesis of (open source) collaboration...
